stages:
  - initial
  - test

# ------------- Initial Stage -------------

.list-env: &list-env
  - PREFIX="$(dirname $(which python))/.."
  - if [ -d "${PREFIX}/conda-meta" ]; then
      conda list --prefix "${PREFIX}" --show-channel-urls;
    else
      python -m pip list installed;
    fi

.test-python: &test-python
  stage: initial
  image: python
  script:
    - python -m pip install .
    - *list-env
    - python -c "import nullcal"
    - python -c "import nullcal.likelihood"
    - for script in $(pip show -f nullcal | grep "bin\/" | xargs -I {} basename {}); do
          ${script} --help;
      done

basic-3.10:
  <<: *test-python
  image: python:3.10


# ------------- Test Stage -------------
.unit-tests: &unit-test
  stage: test
  script:
    - python -m pip install .
    - *list-env
    - python -m unittest discover -s test

python-3.10:
  <<: *unit-test
  needs: ["basic-3.10"]
  image: python:3.10