[default]
extend-ignore-re = [
  "(?s)(<!--|#|//|/\\*)\\s*typos:off.*?\\n\\s*(<!--|#|//|\\*/)\\s*typos:on",
  "(?Rm)^.*(<!--|#|//)\\s*typos:disable-line\\s*.*?(-->)?$",
  "(<!--|#|//)\\s*typos:ignore-next-line\\s*.*?(-->)?\\n.*",
]

[default.extend-words]
afins = "afins"
automodule = "automodule"
autosummary = "autosummary"
autoupdate = "autoupdate"
axvline = "axvline"
bilby = "bilby"
Borkowski = "Borkowski"
covs = "covs"
errorbar = "errorbar"
errorbars = "errorbars"
fftd = "fftd"
ffts = "ffts"
figsize = "figsize"
flen = "flen"
fontsize = "fontsize"
freqs = "freqs"
funcs = "funcs"
gaussianity = "gaussianity"
geocent = "geocent"
idxf = "idxf"
idxm = "idxm"
ifos = "ifos"
imin = "imin"
interp = "interp"
irfft = "irfft"
itrf = "itrf"
kstest = "kstest"
labelsize = "labelsize"
levelname = "levelname"
logfreqs = "logfreqs"
mult = "mult"
nfreqs = "nfreqs"
njit = "njit"
noqa = "noqa"
nullcal = "nullcal"
numba = "numba"
numpy = "numpy"
Nwin = "Nwin"
Nyquist = "Nyquist"
objmode = "objmode"
orthogonalization = "orthogonalization"
Orthogonalized = "Orthogonalized"
periodogram = "periodogram"
phif = "phif"
phitilde = "phitilde"
prange = "prange"
preare = "preare"
prefactor = "prefactor"
Prefactors = "Prefactors"
pvalue = "pvalue"
pylint = "pylint"
pyproject = "pyproject"
rcfile = "rcfile"
recalib = "recalib"
rotvec = "rotvec"
rowvar = "rowvar"
rtol = "rtol"
scipy = "scipy"
stft = "stft"
tlen = "tlen"
toctree = "toctree"
tukey = "tukey"
wavepacket = "wavepacket"
wdata = "wdata"
xarm = "xarm"
xform = "xform"
xlabel = "xlabel"
xlim = "xlim"
XPHM = "XPHM"
xscale = "xscale"
yarm = "yarm"
yerr = "yerr"
ylabel = "ylabel"
